language: go
go:
- 1.8
script:
- env GOOS=linux GOARCH=arm go build -v
- mv homeautomation homeautomation_raspberrypi
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BuTN2K+xxbQ7IBpJ0VY+F07tPzrnAJRRFHnkoGEzS68gR9aI/Igne/GvYW5G7R/wB6phrztggPrJ1gs4oFb2ZgUYTQAat+qeVHbD9SQss4YJQngwEPExIVdg6dR5baXrgItWOMzLZfg1sV/x5Af18bdyOM9NfC09eDQp1dHkMfoPwRha4pJr6laU0cpazf3hjQC3v8JEQikTb6r4nV25xHGEgVg+UFavZIyQhqSqsqaLT9XmuO28YkZdYsz+2ah2I+Sh3EyBFT6if3mHXws54O+neOEZCTYHMHw0jQdlT/27m0d4QzRM2jb+4wIebI6wXmy7Q2arxETyxh7DS2XZ2NAPzvNHTJ7EiyoP6lGcBcGSBPYFud4G4GgB1elUGlwt0GSfFnmbQaLigB6n4aaCY68jw8O8a2ISNA9UknOTZcwE4vfiSVBTjxq9v58eE7fIduVoKhC9wwML9gkivAn5eeDjib386sdVH+QoHkzVT/nk7imkRMrSyJt859r3I1EjxKsuSuOGv9+cyHx36sbPs1VcEmso7OEmDc7SwmuYXyctkOOjcQds0OfMxjCAyDVTCvq2pH0pYjjkn2wAZoSwPUwakcO07lT911IKfpsrniy/NUo4FHPlITAeRSVBHUmWiyVDMx0bWxz4+J2DpZ2cx+JaPDPWxe2bKXrRxC7nGKI=
  file: 
    - homeautomation_raspberrypi
  on:
    repo: orktes/homeautomation
