language: go
go:
- 1.13
script:
- env GOOS=linux GOARCH=arm go build -v
- mv homeautomation homeautomation_raspberrypi
deploy:
  provider: releases
  api_key:
    secure: oDd+3rb+OllajrED632mZm33M0P46ymCJFmNCTHrtrAi/Mr+RV7VmTch4ZeGWRWv4FOWIoy9n5l9DyvrYR5tu02UWjyLuPoJCkWPabfLeEmrxhYvJxbQm0mx5CvGIXhY4gjUSFsuZBSJc5DGJ1CdFIRZQOKhAEpWSlUj49YC8VIG8TD6CsdeyHvVquEFn681c6sqyI4bBv7+qNaq/WZgrOFtPfokP6DlZyq890Heo+6uunNVZVSGrLu3Rl7hiX3HuHQ3tGe596Olh/aYrDQQEk7VS29Y0vcfOHzrQaRyTEGysaLJ3VcCrPb5JppJWN8ISPMfdpqo3NC1oP3Kk/zKAywrBKieOTQ4nSo9uwd2bJ0xuGH3CoQkEJbnXgUOuCfPihXCNIcak7G1BoUumbn9t4O/iHSz2k2CArdmTIcACjIxLHkCEsWI+iXhqvPkKW6R+FP3qQerKTfPMPMWOrRzbm9xMRIJAEHPYnDC4vPmykqxefnJVvKdk36RN2G4Sg6ros5vt25Xz3tLqgB9P0Bp9PakUE6c9Lv/ibzfexQa+w63iUwe/7VKGaFmlQiqtxyB3XYZEXDgr0efx/EQWDxsWknescezlS0DI6O7jFtbIbmD8K0CdEagRQd9Wfe4M0st83YW/cT4qIPsiCK8mihldRk7xALDCHv1bKEPRwlePbM=
  file: homeautomation_raspberrypi
  on:
    repo: orktes/homeautomation
